# **Porque Numpy?**
*  list no tiene buen manejo para los indices cuando se trabaja con listas de datos de más de dos dimensiones.
*  list no posee metodos de algebra lineal, ni de transformaciones de datos.
*  En otros lenguajes encontramos estructuras de datos altamente optimizadas para poder hacer operaciones algebraicas sobre arrays.
*  Por sobre Numpy se erige todo un ecosistema de librerias muy utiles que iremos viendo en el recorrido de este curso.


*  Crear un Array

In [1]:
#Importar la librería
import numpy as np

In [2]:
a1 = np.array([1,2,3])                 # con una lista
type(a1)

numpy.ndarray

In [5]:
a2 = np.arange(10)                 # np.arange es un metodo similar al range del tipo list
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a3 =  np.zeros((2,3))                 # crear un lista de dos dimensiones, pre-rellenada con zeros
a4 =  np.ones((2,3))                 # crear un lista de dos dimensiones, pre-rellenada con unos

In [11]:
from IPython.display import display
display(a3);display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

np.linspace(a,b,n) es una función que permite crear arrays de una dimensión, de largo n, y que contienen puntos entre a y b, distanciados de forma regular. La distancia entre cada punto sera de  (b−a)/(n−1) .

In [13]:
a5 = np.linspace(0,1,11)     #Es ocupado para sacar num aleatorios 
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
# Dtypes
a5.dtype

dtype('float64')

*  Dimensión de un Array

In [16]:
display(a1)

array([1, 2, 3])

In [17]:
a1.shape              

(3,)

In [18]:
display(a3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a3.shape      # dimensión

(2, 3)

In [3]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [21]:
# Son los dos arrays iguales?
np.array_equal(a1D,a2D)

False

In [26]:
# Reshaping
new_dims = (1,a1D.shape[0])
display(new_dims) 
a = a1D.reshape(new_dims)
display(a)
np.array_equal(a,a2D)

(1, 3)

array([[1, 2, 3]])

True

*  Acceso a elementos y Slicing

In [28]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [31]:
a[2,1]

10

Para acceder a un elemento de un array de dimensión n, la síntaxis es  array[i1,i2,i3,...iN] .
En este curso y frecuentemente en ML trabajaremos con arrays de dimensión 1 o dimensión 2, por lo que:
Para un array de 1D:  a[index] 
Para un array de 2D:  a[index1,index2]

In [32]:
a = np.arange(10)
b = np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a[:5]   

array([0, 1, 2, 3, 4])

In [34]:
b[0:3,1]

array([0., 1., 0.])

In [35]:
b[2,0:3]

array([0., 0., 1.])

In [36]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Slicing de arrays

                      # 5 primeros elementos del array a
                      # esta notación nos permite obtener la segunda línea del array b
                      # tercera columna del array b
                      # todo el array b.

*  Operaciones con Arrays

In [39]:
# Aritmetica
a = np.arange(4)

print("a     =", a)
print("a + 5 =", a + 5)
print("a - 5 =", a - 5)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a // 2 =", a // 2)  
print("-a     = ", -a)
print("a ** 2 = ", a ** 2)
print("a % 2  = ", a % 2)

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
-a     =  [ 0 -1 -2 -3]
a ** 2 =  [0 1 4 9]
a % 2  =  [0 1 0 1]



Operator	ufunc
+	np.add
-	np.subtract
*	np.multiply

In [40]:
# Otras ufuncs interesantes
a = np.arange(4)
b = np.arange(1,5)

display(np.exp(a))         # exponencial
display(np.log(b))         # logaritmo natural
display(np.sqrt(a))        # raiz cuadrada
display(np.greater(a,b))   # superior o igual punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [41]:
a

array([0, 1, 2, 3])

In [42]:
b

array([1, 2, 3, 4])

*  Rendimiento

In [44]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for el in a:
    b[i] = el+el
    i+=1

259 ms ± 11.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
%%timeit
a = np.arange(1000000)
a+a

4.44 ms ± 135 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%%timeit
a+a

451 ns ± 6.04 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


*  Estadistica y Aleatoriedad

In [48]:
# Estadística
a = np.arange(10)

display(np.mean(a))           # promedio
display(np.median(a))         # mediana   

4.5

4.5

In [49]:
np.percentile(a,40)                  # percentil

3.6

In [50]:
np.random.random(10) # Aleatoridad

array([0.99328925, 0.8982971 , 0.82141121, 0.75896214, 0.18080205,
       0.42810571, 0.27628226, 0.48327373, 0.04085455, 0.40008862])